### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ravenclaw968** [eltoob/rush#8]
When I type the configuration code, I get:

undefined method 'configure'

Where do I put the configuration code or how do I fix this?

**Comment by reelman** [comment]
Do you have right gem? There are two 'rush' gems and bundle is pulling different gem (at least in my case).

Try if you have the same version:
```
Rush::VERSION
"0.1.0"
```
or/and see if your Gemfile contains
`gem 'rush', git: 'git://github.com/eltoob/rush.git'`

**Comment by eltoob** [comment]
thanks for pointing it out ... will fix the readme
